### ISSUE TITLE
Problem with tulind and talip

### ISSUE THREAD

**Issue by alvarheras** [xFFFFF/Gekko-BacktestTool#16] opened 2018-05-06 17:04 UTC
Hi, there,

I am encountering an **error when I add strategies that use tulind and talip**, the error is as follows. But when I change the settings and add only strategies that don't use tulip indicators it works, do you know what might be happening?

![captura de pantalla 2018-05-06 a las 19 04 37](https://user-images.githubusercontent.com/11508953/39675783-5ad5d1e4-5160-11e8-8255-a119ac3baa1a.png)
![captura de pantalla 2018-05-06 a las 19 04 58](https://user-images.githubusercontent.com/11508953/39675784-62b2aafe-5160-11e8-8873-417e7a234acc.png)

**Currently I am supposed to have the tulind and talip installed as the strategies within gekko ui work correctly**

**I wanted to add a rookie question, how can you set up minutes, hours or days for the test?**

Thank you

**Comment by xFFFFF** [comment] 2018-05-08 07:33
Error from second screenshot is fixed in open source by #17

Error from first screenshot is comes from the gekko, not BT. UI displays less information, maybe it does not appear there. I have the same error when using the CUSTOM_CCI strategy. But I do not know what the cause is. Other strategies, also with tulip and Talib don't produce this error.

You can add candles in @warms in backtest-config.pl. Format is candleSize:warmup-period. Values are in minutes so 5:144 mean candle 5 min and warmup period 12h.

**Closed** 2018-05-17 06:37 UTC

**Comment by alvarheras** [comment] 2018-05-17 19:36
I'm fixing the problem. THANKS!
